vich_uploader:
    db_driver: orm

    mappings:
        avatars:
            uri_prefix: "%uploads_path_avatar%"
            upload_destination: "%kernel.project_dir%/public/%uploads_path_games%"
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_remove: false
        games:
            uri_prefix: "%uploads_path_avatar%"
            upload_destination: "%kernel.project_dir%/public/%uploads_path_games%"
            namer: Vich\UploaderBundle\Naming\UniqidNamer
